### ISSUE TITLE
Question on what one line of codes purpose is

### ISSUE THREAD

**Issue by linuxunil** [dylanaraps/pywal#116]
In sort_colors this line is at the top. 

`raw_colors = colors[:1] + colors[9:] + colors[8:]` 

I understand what it does but not why it is there.  Running it in the REPL didn't seem to enlighten me either.

**Comment by dylanaraps** [comment]
`pywal` generates 16 colors from the image but only 10 are used. That line sorts the 16 colors so that the ordering is like this:

```
color[0], color[9]. color[10]. color[11], color[12], color[13], color[14], color[15], color[8], color[9]. color[10]. color[11], color[12], color[13], color[14], color[15]
```

`pywal` does this because the other colors are either too dark on the background or various shades of grey. The colors from `1-7` don't have enough contrast on the background nor do they create a nice looking colorscheme.

**Comment by linuxunil** [comment]
Ok that makes sense now.  I'm going do put your last comment in that function (summed up a bit) so it makes a bit more sense.
