### ISSUE TITLE
Alpha/Opacity in Rofi

### ISSUE THREAD

**Issue by dr-io** [dylanaraps/pywal#129]
Is there any way to pass alpha settings to Rofi due to it's '--opacity' capability being removed?

Rofi currently relies on argb for alpha and I'd like to work out how to do this whilst running wal

**Comment by Clyybber** [comment]
This would need to be implemented in wal.

**Comment by dylanaraps** [comment]
This will be possible once https://github.com/dylanaraps/pywal/pull/142 is merged. You'll be able to define your own `rofi` variables by overwriting the default template file.

**Comment by dylanaraps** [comment]
This will be really easy in the next `pywal` version as `pywal` now supports user templates.

Example: 

1. Make a file called `colors-rofi.Xresources` in `~/.config/wal/templates`.
2. Set the Xresources for `rofi` to your liking.
   - You can use wal color variables.
3. Run `wal`
4. `wal` will use your new file instead of the built-in one.

Example File with opacity:

```
#define BG #CC{background.strip}
#define HI #CC{color1.strip}
#define FG {color15}
#define TX {color15}

! State:           bg, fg, bg2,  hlbg, hlfg
rofi.color-normal: BG, FG, BG,   HI,   TX
rofi.color-active: BG, FG, BG,   HI,   TX
rofi.color-urgent: BG, HI, BG,   HI,   FG
rofi.color-window: BG, BG, BG
```
