### ISSUE TITLE
Handle foreground/background colors

### ISSUE THREAD

**Issue by opatut** [dylanaraps/pywal#15]
Currently, foreground and background are set to colors 15 and 0 respectively everywhere. Now that I can specify my own color scheme with `-f` (:wink:), I'd like to be able to specify different colors for these (and probably also cursorColor).

This probably needs a bit of refactoring in format_colors and export_colors, mostly. I'll see in the following days if I can prepare a little pull request :blush:

**Comment by dylanaraps** [comment]
This shouldn't be too hard to implement.

The colorscheme file (assuming we keep the same format) will then look something like this:

```sh
#3A5130
#FAF9F5
#FAF9F5
#3A5130
#E3A19D
#E1CEAE
#D6DDCC
#F1D2CB
#F5E9D6
#F9F0E5
#FAF9F5
#999999
#E3A19D
#E1CEAE
#D6DDCC
#F1D2CB
#F5E9D6
#F9F0E5
#FAF9F5
```

This is a bit more complicated and makes editing it a little difficult. Before it was just `0-15` so you could use line numbers to figure out what each color was. I'll look into a config format we can parse so that it's easier for users to modify and use the colorscheme files.

**Comment by dylanaraps** [comment]
See #13

**Comment by opatut** [comment]
Love that solution :)
