### ISSUE TITLE
Pywal produces unreadable colorscheme

### ISSUE THREAD

**Issue by moogypoog** [dylanaraps/pywal#180]
After installing pywal, python3 + pip, xorg, xrdb, feh, imagemagick, urxvt and i3wm, running

`wal -c -i /home/mewlord/Background.jpg`

produces a full colorscheme as expected, exports to xrdb, and is able to set the background with feh, but the text in urxvt is undreable due to the colors produced by pywal. I have tried multiple images, but the result is the same.

# Screenshot 1
![screenshot1](http://oi66.tinypic.com/2qalies.jpg)

# Screenshot 2 (Different image)
![screenshot2](http://oi63.tinypic.com/27y51dy.jpg)

**Comment by dylanaraps** [comment]
Have you tried another terminal emulator?

**Comment by moogypoog** [comment]
I tried both termite and terminator, with no difference. The text colors are equally unreadable. I have also tried using other terminal tools such as ranger. The text is still unreadable so its not a problem on vims part, for example.

**Comment by deviantfero** [comment]
It could be useful to see what kind of wallpapers you're feeding pywal with, could you post one so we can reproduce?

**Comment by moogypoog** [comment]
this was one of the images

https://pre00.deviantart.net/0861/th/pre/i/2017/114/f/6/light_drizzle_by_ishmam-db6kw12.png

the other one i cannot find, it was an image of space.

**Comment by bludot** [comment]
I get same issue:

(not used for terminal but same idea)
![image](https://user-images.githubusercontent.com/2181540/37648360-086ef918-2c2f-11e8-80d6-a547a965bfb5.png)

![image](https://user-images.githubusercontent.com/2181540/37648507-75750e94-2c2f-11e8-92da-2f78d21278b4.png)

**Comment by deviantfero** [comment]
these are the two colorschemes I get from those images, seems readable enough on my end, though I'll agree that for image 2 courtesy of @bludot, the colors a a tad too similar, I'm guessing this is more of an issue with how `pywal` grabs it's colors, rather than something not working as it should.

**Image 1 from @moogypoog **
![colorscheme1](https://i.imgur.com/c0SVD8q.png)

**Image 2 from @bludot **
![colorscheme2](https://i.imgur.com/LEGV6PL.png)

for @moogypoog, are you using `wal.vim` for a colorscheme in vim? seems that comments are giving you an issue, try `:hi Comment ctermfg=2`, to see if that can help you out.

**Comment by dylanaraps** [comment]
Closing this as there's now 5 color backends.
