### ISSUE TITLE
colors: Konsole not supported?

### ISSUE THREAD

**Issue by 3k2** [dylanaraps/pywal#24]
Hi

When I'm using konsole as terminal then use wal to change colors it doesn't appear to change all the colors as it should? 

[I've used to wal to change blue/whie coloring](http://i.imgur.com/1QjG5xt.png)
[Then it should change to dark/dark violet coloring but leaves some areas still blue/white](http://i.imgur.com/mdCPlY6.png)

does this just mean that Konsole terminal is not supported or am I doing something wrong?

**Comment by dylanaraps** [comment]
I just tested in `konsole` and can confirm that the escape sequences don't work. Only the background color is changed when I use `wal`.

I'll do some digging and see if there's an alternative sequence or a reason for it not working.

**Comment by dylanaraps** [comment]
This link implies that `konsole` only supports setting the `background` and `foreground` colors using escape sequences. It's from 2009 so we can't be sure that the info is still correct.

http://kde.6490.n7.nabble.com/Konsole-escape-codes-td1259043.html

> ...For the whole display, Konsole supports the control sequences for
changing the 'text foreground color' and 'text background color'...

Edit: I can't seem to find anything else online. The fact that it doesn't work makes me think it isn't supported altogether. I'll look into getting `wal` to generate `konsole` colorscheme files directly. This way you can load the colors as a regular scheme.

**Comment by dylanaraps** [comment]
`wal` now generates a Konsole colorscheme in the cache directory (`~/.cache/wal/colors-konsole.colorscheme`). This file can be imported into Konsole to apply the colorscheme. This unfortunately can't be done automatically by `wal` but it's better than nothing.

I tried symlinking the file to Konsole's theme directory but from my findings Konsole doesn't reload the colorscheme until you reopen it so that won't work.

**Comment by boardfish** [comment]
I've just made the switch to Konsole myself, and in the theme script I've written, copying the colorscheme to either of Konsole's theme directories (not sure which one is the silver bullet) does the trick. This might be because i3 is refreshed, but I'm not sure. Konsole seems like a formidable choice for a terminal now that this is possible.

**Comment by dylanaraps** [comment]
Are you able to write a little something explaining this in the wiki entry for Konsole? It'll get lost here in the closed issue.

https://github.com/dylanaraps/pywal/wiki/Customization#konsole

**Comment by boardfish** [comment]
Alright, I'll add that in sometime today. On 29 Aug 2017 12:01, Dylan Araps <notifications@github.com> wrote:Are you able to write a little something explaining this in the wiki entry for Konsole? It'll get lost here in the closed issue.
https://github.com/dylanaraps/pywal/wiki/Customization#konsole
