### ISSUE TITLE
Pywal doesn't write to .Xresources 

### ISSUE THREAD

**Issue by amineden** [dylanaraps/pywal#286]
I installed pywal the other day, it's working great so far, today I wanted to configure it with i3wm, when I found out that it's not writing changes to the .Xresources file, I tried with .Xdefaults but it didn't work either, but running ``xrdb -query `` shows the active color scheme 
how can I make it write changes to .Xresources

**Comment by deviantfero** [comment]
this expected behaviour @amineden, `pywal` tries to be as non-intrusive as possible, and it accomplishes this by having it's own .Xres format output somewhere else, xrdb doesn't really care where the color-scheme actually is when you call it explicitly, you can find this outputs i'm talking about under `~/.cache/wal/colors.Xresources`

as for writing the file directly to your `.Xresources` (which I don't recommend), you could use the `-o` flag to run a script that copies that `colors.Xresources` I mention earlier to overwrite your `.Xresources`

how are you having trouble with i3wm anyway? care to give more details?

**Comment by ltgouvea** [comment]
@amineden  Here's my `.Xdefaults` if you need an example
[.Xdefaults.txt](https://github.com/dylanaraps/pywal/files/2272188/default.Xdefaults.txt)

Try to run `xrdb -merge .Xdefaults` (or `.Xresources` if you want to, my `.Xresources` is just a symlink to `.Xdefaults` and works fine).

Note that I copy the `~/.cache/wal/colors.Xresources` file to my home folder and include it in `.Xdefaults` with `#include "/home/k2/colors.Xdefaults"`

**Comment by amineden** [comment]
> this expected behaviour @amineden, pywal tries to be as non-intrusive as possible, and it accomplishes this by having it's own .Xresources file output somewhere else, xrdb doesn't really care where the file is when you call it explicitly, you can find this output file i'm talking about under ~/.cache/wal/colors.Xresources
> 
> as for writing the file directly to your .Xresources (which I don't recommend), you could use the -o flag to run a script that copies that colors.Xresources I mention earlier to overwrite your .Xresources
> 
> how are you having trouble with i3wm anyway? care to give more details?
i3wm wasn't using the pywal colors, I thought it was related to .Xresources, turns out there was a problem in my i3 config, I fixed it.
thanks for the information anyway.
