### ISSUE TITLE
Multiflag support does not follow UNIX standard

### ISSUE THREAD

**Issue by tzcrawford** [dylanaraps/pywal#303]
It appears that pywal takes some flags as priority over others. For instance,`wal -f -h 3024` only outputs the help to the terminal and does not set the theme to 3024.
Likewise, you cannot specify that you are done entering option flags w/ `--` e.g. `wal -f -- "$(rofi -dmenu <  FileListingAllThemes)"` although, `wal -f "$(rofi -dmenu <  FileListingAllThemes)"` does work. See [http://wiki.bash-hackers.org/dict/terms/end_of_options](http://wiki.bash-hackers.org/dict/terms/end_of_options)

**Comment by lasers** [comment]
`-f`, `-h` is optional arguments. There are no priorities and `-h` does what it says... which is to `show this help message and exit`. Otherwise, we can have `wal` running `wal -f 3024` to change everything then `print_help()` literally right at end of `wal`...  which would be stupid imho.

I don't understand why we need to specify that we're done specifying optional arguments because there are no positional arguments in `wal --help`.

* I think the command `wal -f -- "$(rofi -dmenu <  FileListingAllThemes)"` is invalid.
* I think the command `wal -f "$(rofi -dmenu < FileListingAllThemes)"` is valid.
* `FileListingAllThemes` should be a list of valid themes without leading `-`.

Maybe you can tell us more about the specific issue you're having.
