### ISSUE TITLE
Termite issue on light themes

### ISSUE THREAD

**Issue by aleprovencio** [dylanaraps/pywal#316]
Hello, I'm aware of https://github.com/dylanaraps/pywal/issues/175 but I still get this bug and can't use light themes on termite.

This is arch on:
```
community/python-pywal 3.1.0-2
extra/vte-common 0.54.1-1
community/termite 13-3
```
Thanks!

**Comment by dylanaraps** [comment]
This is a termite issue and not a `pywal` one.

**Comment by aleprovencio** [comment]
Sorry about that, should have checked other vte based terminals before.
Just filled an issue https://github.com/thestinger/termite/issues/638

**Comment by egmontkob** [comment]
`pywal` _could_ set the bold color (OSC 5;0), supported by VTE since 0.52.1. And while there, also set 5;1 thru 5;4 for [underline, italic etc. colors](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands) supported by xterm and presumably some others (but not VTE).

I'm not sure if it _should_, though, or just let users make sure they don't use these weird features, it's up for you to make a decision here.

**Comment by dylanaraps** [comment]
I can't seem to get the sequence to work. Got a test `printf` command I can use?

**Comment by egmontkob** [comment]
VTE supports this escape sequence beginning with version 0.52.1. Termite requires a fork called vte-ng whose newest version is based on VTE 0.52.2. So there's an overlap here. I have actually tried Termite with vte-ng 0.52.2-ng and it works.

> Why not just fix the VTE bug?

What VTE bug, again? I believe all the bugs we're aware of, including the one you were kind to report, have been fixed.

The current behavior of VTE, including how it handles bold, is per design since version 0.52 (or 0.52.1 with the addition of OSC 5;0).

Moreover, beginning with 0.54 it no longer prints garbage on unrecognized escape sequences.

Obviously there's no way we could retroactively fix older versions. If you need to make the very same escape sequence work with all the versions, you need to find ugly hacks such as saving-restoring the cursor as you did, or rework your code so that instead of cat'ing one fixed file it could be a shell script that outputs different things based on runtime VTE_VERSION.

**Comment by aleprovencio** [comment]
@dylanaraps, should we open a new issue report on this based on @egmontkob's statement above?

**Comment by aleprovencio** [comment]
FYI, it's been working for me without workarounds. Can't point which commit, but thanks for that.
