### ISSUE TITLE
Option to exclude apps?

### ISSUE THREAD

**Issue by catzybluphish** [dylanaraps/pywal#344]
Is there a way to exlude vim or other applications from being colored by pywal? It usually makes the syntax highlighting indistinguishable.
Cheers.

**Comment by deviantfero** [comment]
hey, sorry for the late answer, anyway, you have no need of using the colorscheme that pywal provides for vim if you don't need it, just choose another color-scheme in vim for instance, like

`:colorscheme nord`
or something like that

another thing you could try is another wal backend, so that you get different colorschemes

**Comment by GloverDonovan** [comment]
What do you mean by "makes the syntax highlighting indistinguishable"? This sounds like a problem with your vim config or terminal emulator instead of pywal. It would help if you provide a screenshot and your `.vimrc`.

**Comment by Mati20187** [comment]
I have pretty much the same question. Is it possible to choose which applications I want colored? For example, I only want pywal to change the color scheme of rofi.
