### ISSUE TITLE
generated GTK themes seem forced to be Numix-based

### ISSUE THREAD

**Issue by Patricol** [dylanaraps/pywal#351]
Themes generated by pywal when the below configuration is present in ~/.config/wal/templates/colors-oomox have Numix-style elements; (e.g.: checkboxes) instead of Materia-style elements.

Oomox correctly interprets the below configuration as a Materia-based theme; which can be tested by opening Oomox and importing the file pywal generates (~/.cache/wal/colors-oomox) as an Oomox colors file.

> NAME=wal
> THEME_STYLE=materia
> BG={color0.strip}
> FG={color15.strip}
> MENU_BG={color0.strip}
> MENU_FG={color15.strip}
> SEL_BG={color9.strip}
> SEL_FG={color0.strip}
> ACCENT_BG={color9.strip}
> TXT_BG={color13.strip}
> BTN_BG={color8.strip}
> BTN_FG={color0.strip}
> ROUNDNESS=4
> GTK3_GENERATE_DARK=False
> MATERIA_STYLE_COMPACT=True
> TXT_FG={color15.strip}

Let me know if you need any extra information.

**Comment by dylanaraps** [comment]
I've sick of trying to work with GTK. `wpgtk` has great GTK support.

**Comment by Patricol** [comment]
Could you leave it open with help-wanted?

Pywal is such a fantastic program; it's not hard to imagine someone wanting to submit a pull request for this.

Or do you plan to reduce/remove GTK support?

**Comment by deviantfero** [comment]
As stated in other issues Dylan plans to drop GTK support for pywal, you
can still get these features in `wpgtk`, it has a dedicated gtk theme for
this purpose so it's a lot faster than oomox too (and has live reload even
for GTK+), you could also generate a theme in a similar fashion using
pywals user templates though, but it's way more work that way.

On Jan 4, 2019 9:03 PM, "Patrick Collins" <notifications@github.com> wrote:

Could you leave it open with help-wanted?

Pywal is such a fantastic program; it's not hard to imagine someone wanting
to submit a pull request for this.

Or do you plan to reduce/remove GTK support?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dylanaraps/pywal/issues/351#issuecomment-451622593>,
or mute
the thread

**Comment by dylanaraps** [comment]
It's more than a pull request. It needs a maintainer also.
