### ISSUE TITLE
[feature request] Preserve color ordering

### ISSUE THREAD

**Issue by polyfloyd** [dylanaraps/pywal#363]
CLI programs often rely on colors to convey information to the user. E.g. `git diff` uses red lines to show lines that were removed and green for lines that were added. 

When pywal generates a colorscheme for terminals, it disregards the meaning of the original colors which can make it harder to use these programs.

I think it would be useful for pywal to be able to order the generated colorscheme so the colors resemble the original standard colors.

**Comment by dylanaraps** [comment]
I'll look into this. I don't think it's possible however. The color-schemes are generated from images which most of the time don't have all of the colors. `pywal` does support predefined themes of which it has a ton. These all adhere to the color ordering.

**Comment by deviantfero** [comment]
hi @dylanaraps, there's something really similar already implemented in `wpgtk`, for the lack of a better named it's called `smart sort`, it orders the colors according to how close they are in an euclidean distance formula to the standard terminal colors, so the redest color will go to spot 1 (from 0 - 15), the greenest from to spot 2, and so on.

as a consequence some might say that the color schemes are less diverse, so I made it the default, but you can disable that setting, here you can see the implementation:

https://github.com/deviantfero/wpgtk/blob/master/wpgtk/data/color.py (search for `smart_sort` function)

here's the result:

*pywal's result (without any adjustment)*
[pywal](https://i.imgur.com/PwCazON.png)

*after auto-adjust and smart sort*
[wpgtk](https://i.imgur.com/ZXy8vgs.png)

As you can see it's not perfect, since there's no red-est color (only magenta-est color) an illogical placement is made, you can easily edit that color to be redder and it will fit right in place with the standard, so it can definitely be improved

**Comment by eugeene** [comment]
I don't know if my 'issue' fits. But let's say I'd like to have a blue pywall-generated palette based on blue wallpaper but I'd like to keep color1 red and color3 yellow for errors and warning messages in terminal.

In .zshrc I am currently trying to use this:
```
xrdb -merge $HOME/.cache/wal/colors.Xresources
xrdb -merge $HOME/.dotfiles/X11/Xdefaults
```

but that is not working well. Is there any way to achieve that? Thanks

**Comment by dylanaraps** [comment]
I recommend using `wpgtk` for this feature.
