### ISSUE TITLE
Question: How to temporally disable Pywal?

### ISSUE THREAD

**Issue by ig-perez** [dylanaraps/pywal#585]
I'm troubleshooting some conflicts with Emacs themes and I would like to temporally disable Pywal to see how that affects Emacs, but I couldn't find an option for this in the command line arguments.

Is there an easy way to do this without editing the `.bashrc` file?

Thanks!

**Comment by alt-romes** [comment]
Since Pywal changes terminal colors through escape sequences it wouldn't be clean to have that kind of option. Pywal is "as out of the way as possible", so if you don't want its colors when you start a session, editing the bash configuration temporarily seems like the best option. You could possibly add a variable to control whether to use Pywal colors or not, but I think commenting and uncommenting the line temporarily is a good enough way to do it.

**Comment by ig-perez** [comment]
Yeah, sounds reasonable. Thanks @alt-romes
