### ISSUE TITLE
Sequences enable transparency by default in Foot terminal

### ISSUE THREAD

**Issue by RicArch97** [dylanaraps/pywal#599]
Using the Foot terminal, and the following line in `.zshrc`:
```
(cat ~/.cache/wal/sequences &)
```
The background of the terminal is always transparent by default. (about 0.5 in 0.0 - 1.0 range, i'd say)
I have no idea where this comes from, i've tried running with `wal -b "#000000"` and `wal -a 1.0` but it stays transparent.

The only way to get it right now is skip the sequences and let the terminal set the colors by creating a template, but that means there can't be any curly brackets in the config file apart for the where the colors need to be, which makes it really difficult.

**Comment by dnkl** [comment]
This sounds a lot like https://codeberg.org/dnkl/foot/issues/434, which was fixed in https://codeberg.org/dnkl/foot/pulls/435. @RicArch97 any chance you can build and test latest foot from git?

Note that the transparency issue was a bug, plain and simple. Foot didn't actually support setting transparency runtime. But we do now, since https://codeberg.org/dnkl/foot/pulls/437. I also recently added support for changing the selection (highlight) bg/fg colors: https://codeberg.org/dnkl/foot/pulls/440. All this is in latest git.

**Comment by RicArch97** [comment]
@dnkl I should have check Foot's issues before i posted here 😄 . I will test the lastest version!

**Comment by RicArch97** [comment]
@dnkl Tested latest git version and it seems to work correctly now. Thanks for developing the Foot terminal, it feels way faster than Alacritty.

**Comment by dnkl** [comment]
> Thanks for developing the Foot terminal

You're welcome :)

> it feels way faster than Alacritty.

Well, both have their weak and strong points, I believe. But I obviously prefer foot :D
