### ISSUE TITLE
Setting color66 not color16

### ISSUE THREAD

**Issue by rprechelt** [dylanaraps/pywal#6]
Fresh install of `pywall`, and generated a colorscheme from an image. When inspecting the generated scheme, I noticed that `colors.css` generates:

```
:root {
	--color0: #010408;
	--color1: #233238;
	--color2: #083647;
	--color3: #145362;
	--color4: #466A76;
	--color5: #41A4B5;
	--color6: #50ACBA;
	--color7: #65DAE8;
	--color8: #666666;
	--color9: #233238;
	--color10: #083647;
	--color11: #145362;
	--color12: #466A76;
	--color13: #41A4B5;
	--color14: #50ACBA;
	--color15: #65DAE8;
	--color66: #010408;
}
```

I haven't dug into the internals of pywall extensively, but that `color66` should almost certainly be a `color16`, and pywall doesn't set color16 properly in my terminal which supports that hypothesis.

**Comment by dylanaraps** [comment]
`color66` isn't a typo for `color16`.

`color66` is an additional color that is set to the value of `color0`. When you try to use `color0` and bold text is enabled in your terminal `color8` is used instead. This means that instead of getting a black background or text, you're left with a light grey color instead.

The bug here is that `color66` shouldn't end up in the export files.
