### ISSUE TITLE
vim lightline with pywal

### ISSUE THREAD

**Issue by j0ker70** [dylanaraps/pywal#615]
I have already added the wal.vim plugin for vim. But I alse use lightline. How can I customize lightline to work with pywal?

I have added this in my .vimrc.

```
" statusline with lightline
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'wal',
      \ }
```

But this shows too many errors. What can I do?

**Comment by alt-romes** [comment]
Are you using macOS ?
I fixed this by using `vim` 8.2  installed probably by `xcode-select --install` on Big Sur (/usr/bin/vim)
I also had a workaround for it before using the system installed vim, which I might recreate to share if your problem still persists (originally inspired by following some issues starting here https://github.com/dylanaraps/wal.vim/issues/5)

**Comment by j0ker70** [comment]
No, I am using Ubuntu 20.04. and I am using vim 8.1. I installed it from apt package manager. The errors are like this:

```
Error detected while processing function lightline#update[5]..lightline#colorscheme[12]..lightline#highlight:
line 18:
E254: Cannot allocate color guibg=
Error detected while processing function lightline#update:
line 5:
E171: Missing endif
```

**Comment by alt-romes** [comment]
If it were me, I'd try to upgrade vim first, because after I solved lightline's errors, I noticed some highlighting was incorrect (e.g. LineNr, NonText), and decided it would be better to attempt using another stable 8.2 release (perhaps if I had been able to also fix wal.vim's colorscheme highlighting I would have kept the slightly more recent vim ¯\_(ツ)_/¯)

However, I *did* get lightline working, with the following changes (see full file [here](https://gist.github.com/alt-romes/8a5084d09252965c0a383783ca1dcdad)):

<img width="688" alt="Screenshot 2021-08-29 at 11 13 25" src="https://user-images.githubusercontent.com/21295306/131246824-b3a0cf70-c752-42e7-b4b3-b55741cefdf7.png">

**Comment by j0ker70** [comment]
Sorry if this sounds like a really stupid question but I don't know how to apply these changes. Can you tell me how can I?

**Comment by alt-romes** [comment]
You need to find where "wal.vim" plugin is installed, it should be a folder called `wal.vim`, probably somewhere around inside the folder `.vim`.
Inside `wal.vim` there's a file with path `autoload/airline/themes/wal.vim`

You can try running this command to search for it
```
cd ~/.vim && find . -name "wal.vim" | grep autoload/airline/themes/wal.vim
```

You want to replace that file with the one I provided in that gist.

This one line should find and automatically replace it:
```
cd ~/.vim && (curl -L "https://gist.githubusercontent.com/alt-romes/8a5084d09252965c0a383783ca1dcdad/raw/36cc7e516beb994c1bc1268e10a001689d8a5423/(errors%2520workaround)%2520wal.vim" > "$(find . -name "wal.vim" | grep autoload/lightline/colorscheme/wal.vim)")

```

**Comment by j0ker70** [comment]
It's working now. Thank you. I would install Vim 8.2 asap.
