### ISSUE TITLE
Using tmux with pywal?

### ISSUE THREAD

**Issue by wbehrens-on-gh** [dylanaraps/pywal#635]
I'm trying to get setup for using pywal to change the colors on my tmux status line but the only hits I'm getting are from [this]( https://github.com/dylanaraps/pywal/issues/118) issue which doesn't answer my question, my question being how to specify tmux status line colors using pywal

**Comment by k0mmsussert0d** [comment]
I've also been struggling to get pywal working with tmux properly. Shell spawned in a tab gets colors applied by running `(cat ~/.cache/wal/sequences &)` from `.bashrc`, however bottom status line stays olive-green until I manually run `pywal -R`.

**Comment by arcmags** [comment]
Hmm... tmux works great with wal for me (ArchLinux 5.15.8, tmux 3.2a, wal 3.3.0, XTerm 370).

There isn't really a way to specify tmux status line colors using pywal.  tmux simply uses the colors from the terminal it's in.   To specify which of your terminal colors tmux uses, edit *~/.tmux.conf*.

If tmux is already open, then yes, the expected behavior would be that you have to run *wal* to change the terminal colors (which change tmux's colors).
