### ISSUE TITLE
Add support for Kakoune text editor

### ISSUE THREAD

**Issue by AnzenKodo** [dylanaraps/pywal#643]

**Comment by cakekindel** [comment]
hi anzen, I've been a daily kakoune user for a couple years and came across this by accident - this issue should be opened at mawww/kakoune rather than here. pywal sets everything it knows about to the shell environment and would have to bend over backwards to modify kakoune colors. I believe its theming engine makes it almost totally ignore the shell colors. You can get close with `:colorscheme default`
