### ISSUE TITLE
colors.sh breaks if wallpaper name contains a single quote

### ISSUE THREAD

**Issue by SirWrexes** [dylanaraps/pywal#665]
Hey !
Title is self-explanatory.
Have a good day~
![image](https://user-images.githubusercontent.com/5567164/158870334-51c41dda-ce7a-4241-a4bd-4042c7335f04.png)

**Comment by robwaz** [comment]
Are you using the latest version of pywal from github or are you pulling the pypi version?

I looked into the issue, but it doesn't seem to be an issue on github master as it uses `"` instead of `'` to encapsulate the path.  One could argue then that files with `"` in the name do not work.. but IMO... you shouldn't have files with either.

Please let me know if the issue persists on github master version, and I'll submit a PR that'll escape whichever offending character remains.

Cheers

**Comment by SirWrexes** [comment]
I'm using `python-pywal` from Arch's `community` repos.
I'll try with the git version from the AUR and keep you updated by editing this post in a minute.

EDIT: Yup the git version works properly. Thanks !
