### ISSUE TITLE
Is there any reason why pywal's API only works in python > 3.6?

### ISSUE THREAD

**Issue by deviantfero** [dylanaraps/pywal#78]
I've been having a bad time installing pywal in some distros, as they don't ship with python 3.6 nor it's in the native repos of said distributions, so I was wondering if there was any real reason why `python>=3.4` wouldn't work

**Comment by dylanaraps** [comment]
This was my first Python project so I just used whatever was installed on my system and it happened to be `3.6`. I've got a working `3.5` branch on my laptop with the only big issue being that dicts in `<3.6` are unordered so we'll have to swap to using OrderedDict from the `collections` module.

The local branch is also a little messy since the `open()` function doesn't work with `Path` objects in `<3.6` so there's a bunch of `str()` everywhere. There's also no `f-strings` so the formatting had to be replaced with the `%` operator.

I'll work on the branch and clean things up but I'm not going to support anything below `3.5` since it's the newest version that Debian Stable ships with.

**Comment by aeikenberry** [comment]
> There's also no f-strings so the formatting had to be replaced with the % operator

Use `.format()` instead of `%` 🙏  😄

**Comment by deviantfero** [comment]
yes, it seems so, I was just genuinely curious about that detail, if that's the case I'll have to replace those f-strings in `wpgtk`, too. This way much more users will be able to use our software.

**Comment by dylanaraps** [comment]
> Use .format() instead of % 🙏 😄

The modulo operator is faster no? 

I'm assuming so since `format()` is a function and `%` is syntax. The same can be said for `[]`/`{}` and `list()`/`dict()`. The syntax is always faster.

Yes, the `format()` method is much more flexible but we don't really need to use anything other than basic substitutions. (I converted all of the `f-strings` to the `%` format with ease.)

**Comment by aeikenberry** [comment]
It's not a big deal, I just prefer new code being written to use the newer way. `%` will be a little faster, so that's a win.

**Comment by dylanaraps** [comment]
I've opened up #79 which adds support for Python `3.5`. All of the (known) issues are fixed and all that's left is the cleanup of the `str()` litter and some test cleanup. I haven't decided whether or not to remove all `pathlib`/`Path` usage in place of `os.path` and `Strings`.

Anyway, I'll finish this off tomorrow and merge it when I'm happy with it.

**Comment by dylanaraps** [comment]
#79 is done.

I've removed all `pathlib` usage, the `str()` litter and simplified the color `dicts` so we no longer need `OrderedDict`. Adding support for Python `3.4` is now possible (There are only two syntax errors.) though I'm not sure if there are any OS that ship anything below `3.5` by default.

This needs testing and I'm also going to write some more unit tests to cover things I found were missing while creating the PR. I also need to take another look at the API to see if this broke anything (probably not). Let me know if you guys come accross any issues.

The performance is actually a little faster in the Python `3.5` version which makes me more eager to merge this sooner so that's nice. I'm not sure if this was due to the simplification of the `dicts` or not.

**Comment by deviantfero** [comment]
wow, that was fast, will check it out today or tomorrow probably.
